CREATE DATABASE filosoquiz;
USE filosoquiz;

CREATE TABLE RESULTADOS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT
    NOME VARCHAR(512) NOT NULL,
    PONTUACAO INTEGER DEFAULT 0 
    RESULTADO VARCHAR(512)
)